openapi: 3.0.0
info:
  title: Asha-Tai Backend Api's
  version: 1.0.0
paths:
  /product/add:
    post:
      summary: add new product
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: Vaibhav's newly added product with timestamps
              description: This product must be deleted as soon as possible.
              price: 555
              discountPercentage: 99
              rating: 4.69
              stock: 100
              brand: Vb's brand
              category: My products
              thumbnail: https://plus.unsplash.com/premium_photo-1666863911660-d64fc1022c12?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8anBnfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60
              images:
                - https://i.dummyjson.com/data/products/1/1.jpg
                - https://i.dummyjson.com/data/products/1/2.jpg
                - https://i.dummyjson.com/data/products/1/3.jpg
                - https://i.dummyjson.com/data/products/1/4.jpg
                - https://i.dummyjson.com/data/products/1/thumbnail.jpg
      responses:
        "200":
          description: Success
  /product/update/{id}:
    patch:
      summary: update product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            example:
              tags:
                - new
      responses:
        "200":
          description: Success
  /product/delete/{id}:
    delete:
      summary: delete product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /product/all:
    get:
      summary: get products with filters applied
      responses:
        "200":
          description: Success
  /product/getProduct/{id}:
    get:
      summary: get specific product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /order/update/{id}:
    patch:
      summary: update order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            example:
              status:
                - status: pending
                  time: lakjflj
                - status: confirmed
                  time: lakjflj
                - status: canceld
                  time: lakjflj
                  note: Due to out of stock
                  by: admin
              paymentDetails:
                status: confirmed
                method: cash
                amount: 12323
      responses:
        "200":
          description: Success
  /order/createOrder:
    post:
      summary: createOrder
      requestBody:
        required: true
        content:
          application/json:
            example:
              user: id
              items:
                - id: id
                  title: iPhone 9
                  description: An apple mobile which is nothing like apple
                  price: 549
                  discountPercentage: 12.96
                  sellingPrice: 275
                  brand: Apple
                  category: smartphones
                  thumbnail: https://i.dummyjson.com/data/products/1/thumbnail.jpg
                - id: 64eef2b47dd60f087dc2ea16
                  title: iPhone X
                  description:
                    SIM-Free, Model A19211 6.5-inch Super Retina HD display
                    with OLED technology A12 Bionic chip with ...
                  price: 899
                  discountPercentage: 17.94
                  sellingPrice: 450
                  brand: Apple
                  category: smartphones
                  thumbnail: https://i.dummyjson.com/data/products/2/thumbnail.jpg
              priceDetails:
                totalPrice: 1099
                discount: 45
                totalPaid: 799
              address:
                fullName: Vaibhav Bagate
                phoneNumber: "123456780"
                email: test@mail.com
                streetAddress: "test address"
                city: city
                state: state
                pinCode: "123456"
      responses:
        "200":
          description: Success
  /order/all/{id}:
    get:
      summary: getorders of the user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /cart/add:
    post:
      summary: add to cart
      requestBody:
        required: true
        content:
          application/json:
            example:
              user: id
              quantity: 5
              title: Vaibhv's product 2
              description: This is a Vaibhv's product 2
              price: 55
              discountPercentage: 5
              rating: 5
              stock: 55
              brand: Vaibhav
              category: merch
              thumbnail: https://i.dummyjson.com/data/products/6/thumbnail.png
              images:
                - https://i.dummyjson.com/data/products/6/1.png
                - https://i.dummyjson.com/data/products/6/2.jpg
                - https://i.dummyjson.com/data/products/6/3.png
                - https://i.dummyjson.com/data/products/6/4.jpg
      responses:
        "200":
          description: Success
  /cart/get/{id}:
    get:
      summary: get cart items for user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
  /cart/update/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    patch:
      summary: update cart
      requestBody:
        required: true
        content:
          application/json:
            example:
              quantity: 14
              brand: Sumit
              category: sumit's Merch
      responses:
        "200":
          description: Success
  /cart/reset/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    delete:
      summary: reset cart
      responses:
        "200":
          description: Success
  /cart/delete/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    delete:
      summary: delete item from cart
      responses:
        "200":
          description: Success
  /user/get/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: get user by id
      responses:
        "200":
          description: Success
  /user/update/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    patch:
      summary: update User api's
      requestBody:
        required: true
        content:
          application/json:
            example:
              selectedAddress: address_id
      responses:
        "200":
          description: Success
  /auth/signup:
    post:
      summary: signup with password  hasing
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Thor
              email: test@mail.com
              password: Thor123
      responses:
        "200":
          description: Success
  /auth/login:
    post:
      summary: "login "
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: test@mail.com
              password: hashedpasswork
      responses:
        "200":
          description: Success
  /pay/create-order:
    post:
      summary: create order and get session id
      requestBody:
        required: true
        content:
          application/json:
            example:
              user: { { id } }
              items:
                - id: { { id } }
                  title: iPhone X
                  description:
                    SIM-Free, Model A19211 6.5-inch Super Retina HD display
                    with OLED technology A12 Bionic chip with ...
                  price: 899
                  discountPercentage: 17.94
                  sellingPrice: 450
                  brand: Apple
                  category: smartphones
                  thumbnail: https://i.dummyjson.com/data/products/2/thumbnail.jpg
              priceDetails:
                totalPrice: 1099
                discount: 45
                toPay: 799
              address:
                fullName: Full Name
                phoneNumber: "0123456789"
                email: test@mail.com
                streetAddress: "Test Address"
                city: city
                state: state
                pinCode: "12345"
      responses:
        "200":
          description: Success
